config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:new, :create]
  end

  resources :likes, only: [:create]
  delete '/likes', to: 'likes#destroy'
  post '/search', to: 'searches#create'


  devise_for :users
  resources :users, only: [:edit, :update, :show]
  get '/home', to: 'static_pages#home'
  get '/settings', to: 'static_pages#settings'

  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes
  has_many :comments

  has_one_attached :video
  has_one_attached :thumbnail

  before_save do
    num = rand(3)
    if num == 1
      self.recommended = true
    elsif num == 2
      self.recently_watched = true
    else
      self.trending = true
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  belongs_to :country

  has_many :posts
  has_many :likes
  has_many :comments

  validates :username, :phone_number, presence: true, uniqueness: true
  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :username, :phone_number, :country_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.build(post_id: @post.id, body: params[:body])
    @comment.save
    redirect_to @post
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.build(post_id: @post.id)
    @like.save
    redirect_to @post
  end

  def destroy 
    @post = Post.find(params[:post_id])
    @like = Like.find_by(user_id: current_user.id, post_id: @post.id)
    @like.destroy
    redirect_to @post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :author?, only: %i[destroy update]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.video.purge
    @post.thumbnail.purge
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :video, :thumbnail)
    end

    def author?
      unless current_user == @post.user
        redirect_to root_path, alert: "Only author can update or destroy a post"
      end
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def create
    if params[:search] == "michael"
      redirect_to Post.first
    elsif params[:search] == "brazil vs germany"
      redirect_to Post.second
    else
      redirect_to Post.third
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def settings
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
    @minimum_password_length = 6
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_back_or_to @user, notice: "User successfully updated"
    else
      flash.now.alert = 'Could not update user.'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :username, :phone_number, :country_id, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, class: 'form', html: { class: 'container form-floating form p-5' }) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field mb-3'>
    <%= form.label :title, style: "display: block", class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class='field mb-3'>
    <%= form.label :description, style: "display: block", class: 'form-label' %>
    <%= form.text_area :description, style: 'height: 103px;', class: 'form-control' %>
  </div>

  <div class='field mb-3'>
    <%= form.label :video, style: "display: block", class: 'form-label' %>
    <%= form.file_field :video, class: 'form-control' %>
  </div>

  <div class='field d-grid'>
    <%= form.submit 'Create Post', { class: 'btn btn-primary btn-lg'} %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class='container show_post recommended_container p-1'>
  <div class='row text-center'>
    <div class="col">
      <%= video_tag url_for(post.video), controls: true, style: "width: 70%" %>
      <div class="row">
        <% if post.likes.find_by(user_id: current_user.id) %>
          <div class="col liked">
            <%= button_to likes_url, method: 'delete', params: { post_id: post.id }, class: 'p-2 bg-white' do %>
              <strong>Like</strong>
            <% end %>
            <p>Likes count: (<%= post.likes.count %>)</p>
          </div>
        <% else %>
          <div class="col not_liked">
            <%= button_to likes_url, method: 'post', params: { post_id: post.id }, class: 'p-2 bg-white' do %>
              <strong>Like</strong>
            <% end %>
            <p>Likes count: (<%= post.likes.count %>)</p>
          </div>
        <% end %>
        <div class='col'>
          <p>
          <strong>Title:</strong> <%= post.title %>
          </p>
          <p>
          <strong>Description:</strong> <%= post.description %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-3 recommended_container">
      <h2>Recommended Videos</h2>
      <% Post.where(recommended: true).each do |post| %>
        <div>
          <%= video_tag url_for(post.video), controls: true, style: "width: 50%" %>
          <p>
          <strong>title:</strong>
          <%= link_to post.title, post_url(post) %>
          </p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row text-center">
    <div class='col comment_form'>
      <strong>Write a comment:</strong>
      <%= form_with url: post_comments_url(@post), class: 'p-3' do |f| %>
        <div class="field">
          <%= f.text_area :body, style: "height: 155px" %>
        </div>
        <div class="field">
          <%= f.submit "Save Comment", class: 'btn btn-primary btn-lg my-1' %>
        </div>
      <% end %>

    </div>
  </div>

  <ul class="row list-group p-2">
    <div class="col all_comments">
      <% post.comments.each do |comment| %>
        <li class='list-group-item border-bottom border-primary'>
          <p>
          <strong>By:</strong> 
          <%= comment.user.full_name %>
          <small class="text-muted"><%= comment.created_at %></small>
          </p>
          <%= comment.body %>
        </li>
      <% end %>
    </div>
  </ul>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1>All Videos</h1>
  
  <div id="trending_posts" class="row my-5">
    <h2>Trending Videos</h2>
    <% @posts.where(trending: true).each do |post| %>
      <div id="<%= dom_id post %>" class='post col mx-5 p-2'>
        <%= video_tag url_for(post.video), controls: true, size: "300x100" %>
        <p><strong>Posted by:</strong> <%= post.user.email %></p>
        <p><strong>Title:</strong> <%= post.title %></p>
        <p>
          <%= link_to "Likes(#{post.likes.count})", post_path(post) %>
        </p>
        <p>
          <%= link_to "Comments(#{post.comments.count})", post_path(post) %>
        </p>
        <%= link_to 'View Video', post_path(post) %>
      </div>
    <% end %>
  </div>

  <div id="recommended_posts" class="row my-5 trending">
    <h2>Recommended Videos</h2>
    <% @posts.where(recommended: true).each do |post| %>
      <div id="<%= dom_id post %>" class='post col mx-5 p-2'>
        <%= video_tag url_for(post.video), controls: true, size: "300x100" %>
        <p><strong>Posted by:</strong> <%= post.user.email %></p>
        <p><strong>Title:</strong> <%= post.title %></p>
        <p>
          <%= link_to "Likes(#{post.likes.count})", post_path(post) %>
        </p>
        <p>
          <%= link_to "Comments(#{post.comments.count})", post_path(post) %>
        </p>
        <%= link_to 'View Video', post_path(post) %>
      </div>
    <% end %>
  </div>

  <div id="recent_posts" class="row my-5 recently_watched">
    <h2>Recently Watched Videos</h2>
    <% @posts.where(recently_watched: true).each do |post| %>
      <div id="<%= dom_id post %>" class='post col mx-5 p-2'>
        <%= video_tag url_for(post.video), controls: true, size: "300x100" %>
        <p><strong>Posted by:</strong> <%= post.user.email %></p>
        <p><strong>Title:</strong> <%= post.title %></p>
        <p>
          <%= link_to "Likes(#{post.likes.count})", post_path(post) %>
        </p>
        <p>
          <%= link_to "Comments(#{post.comments.count})", post_path(post) %>
        </p>
        <%= link_to 'View Video', post_path(post) %>
      </div>
    <% end %>
  </div>
  
  <% if current_user.admin %>
    <%= link_to "New post", new_post_path %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New post</h1>
  
  <%= render "form", post: @post %>
  
  <br>
  
  <div>
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<% if current_user.admin %>
  <div class='misc_links container p-3 border-top'>
    <%= link_to "Edit this post", edit_post_path(@post) %> |
    <%= link_to "Back to posts", posts_path %>

    <%= button_to "Destroy this post", @post, method: :delete, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="container">
    <div id="carouselExampleIndicators" class="carousel slide col" data-bs-ride="true">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
      <%= image_tag 'hero-img', class: "d-block w-100"  %>
        </div>
        <div class="carousel-item">
      <%= image_tag 'hero-img2', class: "d-block w-100"  %>
        </div>
        <div class="carousel-item">
      <%= image_tag 'hero-img3', class: "d-block w-100"  %>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <div class='fs-3 fst-italic my-4'>
      <p>
        The Olympic Games are an international sports festival, held every four years. The ultimate goals are to cultivate human beings, through sport, and contribute to world peace. Summer Games and Winter Games are held separately.
      </p>

      <p>
      You can find more about it here: <%= link_to nil, 'https://en.wikipedia.org/wiki/Olympic_Games', target: :blank %>
      </p>
    </div>
</div>

app/views/static_pages/settings.html.erb
<div class="container">
  <h1>Settings</h1>

  <div class='user_list'>
    <h2>List of Users</h2>
    <ol class="list-group list-group-numbered">
      <% User.all.each do |user| %>
        <li class='user_card list-group-item'>
          <%= link_to user.full_name, user_url(user) %>
          <% unless user.admin %>
            <%= button_to "Make Admin", user_path(user), method: "patch", params: { user: { admin: true } }, class: 'btn btn-dark' %>
          <% end %>
        </li>
      <% end %>
    </ol>
  </div>

  <!--
    <div>
    <h2>Dark Mode</h2>
    <li data-controller="dark-mode">
    <button data-action="dark-mode#toggle">Toggle Dark Mode</button>
    </li>
    </div>
  -->
</div>

app/views/users/edit.html.erb
<div class="container">
  <h2>Edit Profile</h2>

  <%= form_with(model: @user, html: { class: 'form-floating form p-5' }) do |f| %>
    <%= render "devise/shared/error_messages", resource: @user %>

    <div class="field mb-3">
      <%= f.label :full_name, class: 'form-label' %><br />
      <%= f.text_field :full_name, autofocus: true, autocomplete: "full-name", class: 'form-control' %>
    </div>

    <div class="field mb-3">
      <%= f.label :username, class: 'form-label' %><br />
      <%= f.text_field :username, autofocus: true, autocomplete: "user-name", class: 'form-control' %>
    </div>

    <div class="field mb-3">
      <%= f.label :phone_number, class: 'form-label' %><br />
      <%= f.number_field :phone_number, autofocus: true, autocomplete: "phone-number", class: 'form-control' %>
    </div>

    <div class="field mb-3">
      <%= f.label :email, class: 'form-label' %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control' %>
    </div>

    <div class="field mb-3">
      <%= f.label :country_id, "Country", class: 'form-label' %><br />
      <%= f.select :country_id, Country.all.collect { |c| [c.name, c.id] }, {}, { class: 'form-select'} %>
    </div>

    <div class="field mb-3">
      <%= f.label :password, class: 'form-label' %>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password", class: 'form-control' %>
    </div>

    <div class="field mb-3">
      <%= f.label :password_confirmation, class: 'form-label' %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control' %>
    </div>

    <div class="field d-grid">
      <%= f.submit "Save Profile", class: 'btn btn-primary btn-lg' %>
    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<div class='container p-2'>
  <h2>User Profile</h2>
  <ul class='list-group'>
    <% User.attribute_names.each do |name| %>
      <li class="list-group-item"><%= name %>: <%= @user["#{name}"] %></li>
    <% end %>
  </div>
</div>