config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:new, :create]
  end

  resources :likes, only: [:create]
  delete '/likes', to: 'likes#destroy'
  post '/search', to: 'searches#create'


  devise_for :users
  resources :users, only: [:edit, :update, :show]
  get '/home', to: 'static_pages#home'
  get '/settings', to: 'static_pages#settings'

  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes
  has_many :comments

  has_one_attached :video
  has_one_attached :thumbnail

  before_save do
    num = rand(3)
    if num == 1
      self.recommended = true
    elsif num == 2
      self.recently_watched = true
    else
      self.trending = true
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  belongs_to :country

  has_many :posts
  has_many :likes
  has_many :comments

  validates :username, :phone_number, presence: true, uniqueness: true
  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :username, :phone_number, :country_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.build(post_id: @post.id, body: params[:body])
    @comment.save
    redirect_to @post
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.build(post_id: @post.id)
    @like.save
    redirect_to @post
  end

  def destroy 
    @post = Post.find(params[:post_id])
    @like = Like.find_by(user_id: current_user.id, post_id: @post.id)
    @like.destroy
    redirect_to @post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :author?, only: %i[destroy update]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.video.purge
    @post.thumbnail.purge
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :video, :thumbnail)
    end

    def author?
      unless current_user == @post.user
        redirect_to root_path, alert: "Only author can update or destroy a post"
      end
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def create
    if params[:search] == "michael"
      redirect_to Post.first
    elsif params[:search] == "brazil vs germany"
      redirect_to Post.second
    else
      redirect_to Post.third
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def settings
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
    @minimum_password_length = 6
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_back_or_to @user, notice: "User successfully updated"
    else
      flash.now.alert = 'Could not update user.'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :username, :phone_number, :country_id, :password, :password_confirmation, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='footer text-center bg-secondary p-20' id='footer'>
  All right reserved 2022 | Created by: Avash Ghimire
</footer>

app/views/layouts/_header.html.erb
<!--
  <header>
  <div id="logo">
  <img src="" alt="logo">
  </div>
  <div id="search_bar">
  <input type="text" placeholder="Search Here...">
  <%= image_tag 'research.png' %>
  </div>
  <nav>
  <ul>
  <% if current_user %>
    <% if current_user.admin %>
      <li>
      <%= link_to 'Settings', settings_path %>
      </li>
    <% end %>
    <li>
    <%= link_to 'All Videos', posts_url %>
    </li>
    <li>
    <%= button_to(
      "Log Out",
      destroy_user_session_path,
      method: :delete
    ) %>
  </li>
<% else %>
  <li id="login_link">
  <%= link_to 'Login', new_user_session_url %>
  </li>
<% end %>
</ul>
</nav>
</header>
-->

<nav class="navbar navbar-expand-lg" id='navbar'>
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_url %>">
      <%= image_tag 'fun' %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          </a>
          <ul class="dropdown-menu">
            <% if current_user %>
              <li>
                <%= link_to 'All Videos', posts_url, class: 'dropdown-item' %>
              </li>
              <li>
                <%= link_to 'Edit Profile', edit_user_url(current_user), class: 'dropdown-item' %>
              </li>
              <li>
                <%= link_to 'Profile', user_url(current_user), class: 'dropdown-item' %>
              </li>
              <% if current_user.admin %>
                <li>
                  <%= link_to 'Settings', settings_path, class: 'dropdown-item' %>
                </li>
              <% end %>
              <li>
                <%= link_to 'Dark Mode', '#', class: 'dropdown-item' %>
              </li>
              <li>
                <%= button_to(
                  "Log Out",
                  destroy_user_session_path,
                  method: :delete,
                  class: 'dropdown-item'
                ) %>
              </li>
            <% else %>
              <li><%= link_to 'Login', new_user_session_url, class: 'dropdown-item' %></li>
              <li><%= link_to 'Sign up', new_user_registration_url, class: 'dropdown-item' %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <%= form_with url: '/search', method: 'post', class: 'd-flex' do |f| %>
    <%= f.search_field :search, placeholder: :Search, class: "form-control me-2"  %>
    <%= f.submit "Search", class: "btn btn-outline-dark" %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FunOlympic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <%= render 'layouts/header' %>

    <main id='main'>
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>